[appendix]
== Conformance Class Abstract Test Suite (Normative)

=== GeoSciML XML Encoding Abstract Core

[[conf_gsmlxsd_core,/conf/gsmlxsd-core]]
.GeoSciML XML Encoding Abstract Core
[conformance_class]
====
[%metadata]
identifier:: /conf/gsmlxsd-core  
target:: /req/gsmlxsd-core 

inherit:: OGC 10-025r1 OMXML   Observations and Measurements - XML Implementation 

abstract-test:: /conf/gsmlxsd-core/xsd 

abstract-test:: /conf/gsmlxsd-core/sch 

abstract-test:: /conf/gsmlxsd-core/codelist 

abstract-test:: /conf/gsmlxsd-core/time-zone 

====

=== GeoSciML Basic XML Encoding

[[conf_gsmlxsd-basic,/conf/gsmlxsd-basic]]
.GeoSciML Basic XML Encoding
[conformance_class]
====
[%metadata]
identifier:: /conf/gsmlxsd-basic  
target:: /req/gsmlxsd-basic 

inherit:: /conf/gsmlxsd-core/core 

abstract-test:: /conf/gsmlxsd-basic/xsd 

abstract-test:: /conf/gsmlxsd-basic/sch 

====

=== GeoSciML Extension XML Encoding

[[conf_gsmlxsd-extension,/conf/gsmlxsd-extension]]
.GeoSciML Extension XML Encoding
[conformance_class]
====
[%metadata]
identifier:: /conf/gsmlxsd-extension  
target:: /req/gsmlxsd-extension 

inherit:: /conf/gsmlxsd-core/basic 

abstract-test:: /conf/gsmlxsd-extension/xsd 

abstract-test:: /conf/gsmlxsd-extension/sch 

====

=== GeoSciML GeologicTime XML Encoding

[[conf_gsmlxsd-geologictime,/conf/gsmlxsd-geologictime]]
.GeoSciML GeologicTime XML Encoding
[conformance_class]
====
[%metadata]
identifier:: /conf/gsmlxsd-geologictime  
target:: /req/gsmlxsd-geologictime 

inherit:: /conf/gsmlxsd-core/core 

abstract-test:: /conf/gsmlxsd-geologictime/xsd 

abstract-test:: /conf/gsmlxsd-geologictime/sch 

====

=== GeoSciML Borehole XML Encoding

[[conf_gsmlxsd-borehole,/conf/gsmlxsd-borehole]]
.GeoSciML Borehole XML Encoding
[conformance_class]
====
[%metadata]
identifier:: /conf/gsmlxsd-borehole  
target:: /req/gsmlxsd-borehole 

inherit:: /conf/gsmlxsd-core/core 

inherit:: OGC 10-025r1  OMXML 

abstract-test:: /conf/gsmlxsd-borehole/xsd 

abstract-test:: /conf/gsmlxsd-borehole/sch 

====

=== GeoSciML LaboratoryAnalysis-Specimen XML Encoding

[[conf_gsmlxsd-lab,/conf/gsmlxsd-lab]]
.GeoSciML LaboratoryAnalysis-Specimen XML Encoding
[conformance_class]
====
[%metadata]
identifier:: /conf/gsmlxsd-lab  
target:: /req/gsmlxsd-lab 

inherit:: /conf/gsmlxsd-core/core 

inherit:: OGC 10-025r1  OMXML 

abstract-test:: /conf/gsmlxsd-lab/xsd 

abstract-test:: /conf/gsmlxsd-lab/sch 

====

=== GeoSciML Lite XML Abstract Encoding

[[conf_gsmlxsd-lite,/conf/gsmlxsd-lite]]
.GeoSciML Lite XML Abstract Encoding
[conformance_class]
====
[%metadata]
identifier:: /conf/gsmlxsd-lite  
target:: /req/gsmlxsd-lite 

inherit:: OGC 05-033r9: Annex A 

abstract-test:: /conf/gsmlxsd-lite/SF-0 

====

=== GeoSciML Lite XML Encoding for GML

[[conf_gsmlxsd-lite-31,/conf/gsmlxsd-lite-31]]
.GeoSciML Lite XML Encoding for GML
[conformance_class]
====
[%metadata]
identifier:: /conf/gsmlxsd-lite-31  
target:: /req/gsmlxsd-lite-31 

inherit:: /req/gsmlxsd-lite 

abstract-test:: /conf/gsmlxsd-lite-31/xsd 

abstract-test:: /conf/gsmlxsd-lite-31/sch 

====
