== Conformance

This standard defines a JSON encoding which conforms to the OGC JSON-FG 1.0 encoding rules.

Requirements for one standardization target type are considered:

* Data instance

The normative artefacts for JSON encoding are the JSON Schema files provided online with this specification. Those documents explicitly provide the requirements that must be met by any JSON instance document claiming compliance to this specification. Any requirements that cannot be expressed in JSON Schema are described in the relevant section of this document. Therefore, compliant JSON instances shall:

[arabic]
. validate with JSON Schema files,
. pass compliance tests listed in relevant compliance sections.


Conformance with this standard shall be checked using all the relevant tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the https://docs.ogc.org/pol/08-134r11.html[OGC Compliance Testing Policies and Procedures] and the https://www.ogc.org/how-our-compliance-program-works/[OGC Compliance Testing web site].

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.
