[appendix]
== Conformance Class Abstract Test Suite (Normative)

=== GeoSciML Conceptual

[[conf_gsml-conceptual,/conf/gsml-conceptual]]
.GeoSciML Conceptual
[conformance_class]
====
[%metadata]
identifier:: /conf/gsml-conceptual  
target:: /req/gsml-conceptual 

abstract-test:: */conf/gsml-conceptual/similarity* 

====

=== GeoSciML Core Abstract

[[conf_gsml-core,/conf/gsml-core]]
.GeoSciML Core Abstract
[conformance_class]
====
[%metadata]
identifier:: /conf/gsml-core  
target:: /req/gsml-core 

inherit:: Urn:iso:dis:iso:19156:clause:A.1.1 

inherit:: RFC 3986 

abstract-test:: */conf/gsml-core/uml-entity-name* 

abstract-test:: */conf/gsml-core/uml-cardinality* 

abstract-test:: */conf/gsml-core/uml-abstract* 

abstract-test:: */conf/gsml-core/uml-polymorphism* 

abstract-test:: */conf/gsml-core/quantities-uom* 

abstract-test:: */conf/gsml-core/codelist* 

====

=== GeoSciML Linked Open Data

[[conf_gsml-lod,/conf/gsml-lod]]
.GeoSciML Linked Open Data
[conformance_class]
====
[%metadata]
identifier:: /conf/gsml-lod  
target:: /req/gsml-lod 

inherit:: RFC 3986 

abstract-test:: */conf/gsml-lod/codelistURI* 

abstract-test:: */conf/gsml-lod/identifier* 

abstract-test:: */conf/gsml-lod/byref* 

====

=== GeoSciML Basic Logical Model

[[conf_gsml-basic,/conf/gsml-basic]]
.GeoSciML Basic Logical Model
[conformance_class]
====
[%metadata]
identifier:: /conf/gsml-basic  
target:: /req/gsml-basic 

inherit:: /conf/gsml-core 

abstract-test:: /conf/gsml-basic/geologicfeature-purpose 

abstract-test:: /conf/gsml-basic/geologicevent-non-null 

abstract-test:: /conf/gsml-basic/plane-pol-dip-az-not-null 

abstract-test:: /conf/gsml-basic/linear-trend-plunge-not-null 

abstract-test:: /conf/gsml-basic/quantity-range-order 

abstract-test:: /conf/gsml-basic/quantity-range-repeat 

====

=== GeoSciML Extension Logical Model

[[conf_gsml-extension,/conf/gsml-extension]]
.GeoSciML Extension Logical Model
[conformance_class]
====
[%metadata]
identifier:: /conf/gsml-extension  
target:: /req/gsml-extension 

inherit:: /conf/gsml-basic 

abstract-test:: /conf/gsml-extension/geologicfeature-history 

abstract-test:: /conf/gsml-extension/contact-chronoboundary 

abstract-test:: /conf/gsml-extension/slipComponents-slip 

====

=== GeoSciML Timescale Logical Model

[[conf_gsml-timescale,/conf/gsml-timescale]]
.GeoSciML Timescale Logical Model
[conformance_class]
====
[%metadata]
identifier:: /conf/gsml-timescale  
target:: /req/gsml-timescale 

inherit:: /conf/gsml-basic 

abstract-test:: /conf/gsml-timescale/start 

====

=== GeoSciML Borehole Logical Model

[[conf_gsml-borehole,/conf/gsml-borehole]]
.GeoSciML Borehole Logical Model
[conformance_class]
====
[%metadata]
identifier:: /conf/gsml-borehole  
target:: /req/gsml-borehole 

inherit:: /conf/gsml-basic 

inherit:: ISO 19156 Annex A 

abstract-test:: /conf/gsml-borehole/value-intervalBegin 

abstract-test:: /conf/gsml-borehole/drill-interval-1D 

abstract-test:: /conf/gsml-borehole/drill-interval-1D-CRS 

abstract-test:: /conf/gsml-borehole/value-mappedIntervalBegin 

abstract-test:: /conf/gsml-borehole/interval-1D 

abstract-test:: /conf/gsml-borehole/interval-1D-CRS 

abstract-test:: /conf/gsml-borehole/borehole-position-null 

abstract-test:: /conf/gsml-borehole/borehole-elevation-dim 

abstract-test:: /conf/gsml-borehole/borehole-elevation-CRS 

====

=== GeoSciML LaboratoryAnalysis-Specimen Logical Model

[[conf_gsml-lab-analysis,/conf/gsml-lab-analysis]]
.GeoSciML LaboratoryAnalysis-Specimen Logical Model
[conformance_class]
====
[%metadata]
identifier:: /conf/gsml-lab-analysis  
target:: /req/gsml-lab-analysis 

inherit:: /conf/gsml-basic 

inherit:: ISO 19156 Annex A 

abstract-test:: /conf/gsml-lab-analysis/sampledFeature 

abstract-test:: /conf/ gsml-lab-analysis/accuracy-measure 

abstract-test:: /conf/gsml-lab-analysis/accuracy-vocabulary 

====

=== GeoSciML Lite Logical

[[conf_gsml-lite,/conf/gsml-lite]]
.GeoSciML Lite Logical
[conformance_class]
====
[%metadata]
identifier:: /conf/gsml-lite  
target:: /req/gsml-lite 

inherit:: /conf/gsml-core 

abstract-test:: /conf/gsml-lite/geomtype 

abstract-test:: */conf/gsml-lite/string* 

abstract-test:: */conf/gsml-lite/datetime* 

abstract-test:: */conf/gsml-lite/uri* 

abstract-test:: **/conf/gsml-lite/**user-defined 

abstract-test:: **/conf/gsml-lite/**identifier-unique 

abstract-test:: **/conf/gsml-lite/**identifier-uri 

abstract-test:: **/conf/gsml-lite/**geologicunitview-representativeLithology 

abstract-test:: **/conf/gsml-lite/**geologicunitview-representativeAge 

abstract-test:: **/conf/gsml-lite/**geologicunitview-representativeOlderAge 

abstract-test:: **/conf/gsml-lite/**geologicunitview-representativeYoungerAge 

abstract-test:: **/conf/gsml-lite/**boreholeview-elevation-srs 

abstract-test:: **/conf/gsml-lite/**contactview-contacttype 

abstract-test:: **/conf/gsml-lite/**siteobservationview-symbolRotation 

====
